// <auto-generated />
using System;
using GeneradorDeModelos.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GeneradorDeModelos.Migrations
{
    [DbContext(typeof(FreadContext))]
    [Migration("20260114222707_AddNotificacionTable")]
    partial class AddNotificacionTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GeneradorDeModelos.Models.Comentario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Contenido")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<int>("HiloId")
                        .HasColumnType("int");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("HiloId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Comentarios");
                });

            modelBuilder.Entity("GeneradorDeModelos.Models.Foro", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("NombreForo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK__Foros__3214EC27D3A72AD3");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Foros");
                });

            modelBuilder.Entity("GeneradorDeModelos.Models.Hilo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Contenido")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset?>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetimeoffset")
                        .HasDefaultValueSql("(sysdatetimeoffset())");

                    b.Property<int>("ForoId")
                        .HasColumnType("int")
                        .HasColumnName("ForoID");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int")
                        .HasColumnName("UsuarioID");

                    b.Property<int>("Votos")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK__Hilos__3214EC2783A4929C");

                    b.HasIndex("ForoId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Hilos");
                });

            modelBuilder.Entity("GeneradorDeModelos.Models.MenuItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Icono")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id")
                        .HasName("PK__MenuItem__3214EC270DFECBCF");

                    b.ToTable("MenuItems");
                });

            modelBuilder.Entity("GeneradorDeModelos.Models.Notificacion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("EsLeida")
                        .HasColumnType("bit");

                    b.Property<bool>("EsPersistente")
                        .HasColumnType("bit");

                    b.Property<DateTime>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysdatetimeoffset())");

                    b.Property<string>("Mensaje")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int")
                        .HasColumnName("UsuarioID");

                    b.HasKey("Id")
                        .HasName("PK__Notificaciones__3214EC27");

                    b.HasIndex("UsuarioId", "EsLeida")
                        .HasDatabaseName("IX_Notificaciones_UsuarioId_EsLeida");

                    b.ToTable("Notificaciones");
                });

            modelBuilder.Entity("GeneradorDeModelos.Models.Post", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ContenidoMensaje")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset?>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetimeoffset")
                        .HasDefaultValueSql("(sysdatetimeoffset())");

                    b.Property<int>("HiloId")
                        .HasColumnType("int")
                        .HasColumnName("HiloID");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int")
                        .HasColumnName("UsuarioID");

                    b.HasKey("Id")
                        .HasName("PK__Posts__3214EC27AF5FF2BC");

                    b.HasIndex("HiloId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Posts");
                });

            modelBuilder.Entity("GeneradorDeModelos.Models.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("NombreRol")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id")
                        .HasName("PK__Roles__3214EC272D12B82D");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("GeneradorDeModelos.Models.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTimeOffset?>("FechaRegistro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetimeoffset")
                        .HasDefaultValueSql("(sysdatetimeoffset())");

                    b.Property<string>("NombreUsuario")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("ProfilePictureUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RolId")
                        .HasColumnType("int")
                        .HasColumnName("RolID");

                    b.HasKey("Id")
                        .HasName("PK__Usuarios__3214EC2753326430");

                    b.HasIndex("RolId");

                    b.HasIndex(new[] { "NombreUsuario" }, "UQ__Usuarios__6B0F5AE081C744C4")
                        .IsUnique();

                    b.HasIndex(new[] { "Email" }, "UQ__Usuarios__A9D105345F54D739")
                        .IsUnique();

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("GeneradorDeModelos.Models.Voto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("FechaVoto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetimeoffset")
                        .HasDefaultValueSql("(sysdatetimeoffset())");

                    b.Property<int>("HiloId")
                        .HasColumnType("int")
                        .HasColumnName("HiloID");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int")
                        .HasColumnName("UsuarioID");

                    b.Property<int>("Valor")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK__Votos__3214EC27");

                    b.HasIndex("HiloId");

                    b.HasIndex("UsuarioId", "HiloId")
                        .IsUnique()
                        .HasDatabaseName("IX_Votos_UsuarioId_HiloId");

                    b.ToTable("Votos");
                });

            modelBuilder.Entity("RolMenuItemPermiso", b =>
                {
                    b.Property<int>("RolId")
                        .HasColumnType("int")
                        .HasColumnName("RolID");

                    b.Property<int>("MenuItemId")
                        .HasColumnType("int")
                        .HasColumnName("MenuItemID");

                    b.HasKey("RolId", "MenuItemId")
                        .HasName("PK__Rol_Menu__C1B73DA11E4A5809");

                    b.HasIndex("MenuItemId");

                    b.ToTable("Rol_MenuItem_Permisos", (string)null);
                });

            modelBuilder.Entity("GeneradorDeModelos.Models.Comentario", b =>
                {
                    b.HasOne("GeneradorDeModelos.Models.Hilo", "Hilo")
                        .WithMany("Comentarios")
                        .HasForeignKey("HiloId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GeneradorDeModelos.Models.Usuario", "Usuario")
                        .WithMany("Comentarios")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Hilo");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("GeneradorDeModelos.Models.Foro", b =>
                {
                    b.HasOne("GeneradorDeModelos.Models.Usuario", "Usuario")
                        .WithMany("Foros")
                        .HasForeignKey("UsuarioId")
                        .HasConstraintName("FK_Foros_Usuarios");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("GeneradorDeModelos.Models.Hilo", b =>
                {
                    b.HasOne("GeneradorDeModelos.Models.Foro", "Foro")
                        .WithMany("Hilos")
                        .HasForeignKey("ForoId")
                        .IsRequired()
                        .HasConstraintName("FK__Hilos__ForoID__6754599E");

                    b.HasOne("GeneradorDeModelos.Models.Usuario", "Usuario")
                        .WithMany("Hilos")
                        .HasForeignKey("UsuarioId")
                        .IsRequired()
                        .HasConstraintName("FK__Hilos__UsuarioID__68487DD7");

                    b.Navigation("Foro");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("GeneradorDeModelos.Models.Notificacion", b =>
                {
                    b.HasOne("GeneradorDeModelos.Models.Usuario", "Usuario")
                        .WithMany("Notificaciones")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Notificaciones_Usuarios");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("GeneradorDeModelos.Models.Post", b =>
                {
                    b.HasOne("GeneradorDeModelos.Models.Hilo", "Hilo")
                        .WithMany("Posts")
                        .HasForeignKey("HiloId")
                        .IsRequired()
                        .HasConstraintName("FK__Posts__HiloID__6C190EBB");

                    b.HasOne("GeneradorDeModelos.Models.Usuario", "Usuario")
                        .WithMany("Posts")
                        .HasForeignKey("UsuarioId")
                        .IsRequired()
                        .HasConstraintName("FK__Posts__UsuarioID__6D0D32F4");

                    b.Navigation("Hilo");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("GeneradorDeModelos.Models.Usuario", b =>
                {
                    b.HasOne("GeneradorDeModelos.Models.Role", "Rol")
                        .WithMany("Usuarios")
                        .HasForeignKey("RolId")
                        .IsRequired()
                        .HasConstraintName("FK__Usuarios__RolID__619B8048");

                    b.Navigation("Rol");
                });

            modelBuilder.Entity("GeneradorDeModelos.Models.Voto", b =>
                {
                    b.HasOne("GeneradorDeModelos.Models.Hilo", "Hilo")
                        .WithMany()
                        .HasForeignKey("HiloId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Votos_Hilos");

                    b.HasOne("GeneradorDeModelos.Models.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Votos_Usuarios");

                    b.Navigation("Hilo");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("RolMenuItemPermiso", b =>
                {
                    b.HasOne("GeneradorDeModelos.Models.MenuItem", null)
                        .WithMany()
                        .HasForeignKey("MenuItemId")
                        .IsRequired()
                        .HasConstraintName("FK__Rol_MenuI__MenuI__72C60C4A");

                    b.HasOne("GeneradorDeModelos.Models.Role", null)
                        .WithMany()
                        .HasForeignKey("RolId")
                        .IsRequired()
                        .HasConstraintName("FK__Rol_MenuI__RolID__71D1E811");
                });

            modelBuilder.Entity("GeneradorDeModelos.Models.Foro", b =>
                {
                    b.Navigation("Hilos");
                });

            modelBuilder.Entity("GeneradorDeModelos.Models.Hilo", b =>
                {
                    b.Navigation("Comentarios");

                    b.Navigation("Posts");
                });

            modelBuilder.Entity("GeneradorDeModelos.Models.Role", b =>
                {
                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("GeneradorDeModelos.Models.Usuario", b =>
                {
                    b.Navigation("Comentarios");

                    b.Navigation("Foros");

                    b.Navigation("Hilos");

                    b.Navigation("Notificaciones");

                    b.Navigation("Posts");
                });
#pragma warning restore 612, 618
        }
    }
}
